### ISSUE TITLE
Missing `dist`

### ISSUE THREAD

**Issue by vnourdin** [greyskullrocks/eleventy-plugins#6]
**Describe the bug**
`dist` is missing from the NPM package, so we can't use this plugin from eleventy.

**To Reproduce**
```
npm install --save-dev @greyskullrocks/eleventy-plugin-tinycss
```
Then in your eleventy config :
```javascript
const tinyCSS = require('@greyskullrocks/eleventy-plugin-tinycss');
```
When running eleventy :
```node
Eleventy fatal error: (more in DEBUG output)
> Error in your Eleventy config file '/PATH/TO/11ty/.eleventy.js'. You may need to run `npm install`.

`EleventyConfigError` was thrown
> Cannot find module '/PATH/TO/11ty/node_modules/@greyskullrocks/eleventy-plugin-tinycss/dist/index.js'. Please verify that the package.json has a valid "main" entry

`Error` was thrown:
    Error: Cannot find module '/PATH/TO/11ty/node_modules/@greyskullrocks/eleventy-plugin-tinycss/dist/index.js'. Please verify that the package.json has a valid "main" entry
        at tryPackage (internal/modules/cjs/loader.js:303:19)
        at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (/PATH/TO/11ty/.eleventy.js:10:17)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
```
And, indeed, there is no `dist` folder.

Initially reported [here](https://github.com/greyskullrocks/eleventy-plugins/issues/1) as [NPM is pointing to the wrong repo](https://www.npmjs.com/package/@greyskullrocks/eleventy-plugin-tinycss).

**Comment by Marabyte** [comment]
Hi! Thank you for your feedback!

I'm closing this one in favour of #1 

And I've updated the old repo with the proper instructions.
